### PR TITLE
Parallelize Travis CI

### PR DESCRIPTION
**Pull request by pgev**

### CODE REVIEW

**Comment by schemar** [comment]
Contracts are also compiled multiple times on each run. Maybe that can be optimized in a way.

**Comment by pgev** [comment]
>Contracts are also compiled multiple times on each run. Maybe that can be optimized in a way.

@schemar Definitely. I would propose to have a warm up job and then run tests.

**Comment by schemar** [comment]
Is that possible? To share state of a warmup job with subsequent parallel test VMs?

**Comment by schemar** [comment]
I suggest we merge this as is. It already speeds up the tests to take only half the time.

**Pull request merged**
