### PR TITLE
Update truffle dependency

### PR DESCRIPTION
**Pull request by schemar**
References https://github.com/OpenST/mosaic-contracts/issues/758

### CODE REVIEW

**Comment by schemar** [comment]
I restarted the failing tests, but it appears the updated truffle version may actually result in failing unit tests. Also running the tests locally now.

**Comment by schemar** [comment]
OK there are definitely problems with Truffle `5.0.19` in mosaic contracts.

**Comment by schemar** [comment]
It *may* be necessary to update the git submodules after upgrading the truffle versions there. Not sure. I get errors when I try to compile right now.

**Comment by schemar** [comment]
I _think_ I ended up in git submodule hell :sweat_smile:
contracts includes utiliytoken includes organization. I am not really able to compile any more. I hope this is something I messed up only locally for me ...

**Comment by deepesh-kn** [comment]
> I _think_ I ended up in git submodule hell 😅
> contracts includes utiliytoken includes organization. I am not really able to compile any more. I hope this is something I messed up only locally for me ...

Fixed the issue. Now open for review.

**Pull request merged**
